name: dndice
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  lottie: ^2.6.0
  vibration: ^1.7.4

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/backgrounds/fullbackground.png
    - assets/icons/feather_hand.png
    - assets/icons/back_hand.png
    - assets/icons/
    - assets/logo/splash_logo.png
    - assets/animations/d20_roll.json
  fonts:
    - family: MedievalSharp
      fonts:
        - asset: assets/fonts/MedievalSharp-Regular.ttf

flutter_native_splash:
  color: "#000000"
  android_12:
    color: "#000000"
