name: dndice
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/backgrounds/wood.jpg
    - assets/backgrounds/scroll.png
    - assets/icons/feather_hand.png
    - assets/icons/back_hand.png
    - assets/icons/
  fonts:
    - family: MedievalSharp
      fonts:
        - asset: assets/fonts/MedievalSharp-Regular.ttf
